Principal Component Analysis of uscrime.csv
========================================================

Data Exploration and Data Preparation
-----
```{r}
#Read in the data into a dataframe
uscrime <- read.csv("uscrime.csv")

#Display the first few entries
head(uscrime)

#Display the structure of the data
str(uscrime)

#Summary of the data
summary(uscrime)

#Check for missing values
sum(complete.cases(uscrime))

#Keep the complete cases only
uscrime <- uscrime[complete.cases(uscrime),]

```

Preparing for factorization
---------
1. We prepare the variables for factorization
2. Analyse the factorability using Correlation, significance and also the sampling adequacy

```{r}
# We want to factorize only the variables that make some sense
uscrimepc <- uscrime[,c(4:10)]

library(Hmisc)

#Analyse the Variables Correlation and Significance
rcorr(as.matrix(uscrimepc))

#Check the Kaiser-Meyer-Olkin factor adequacy
#Values above 0.5 are considered adequate.
library(psych)
KMO(uscrimepc)

#Using Bartlett's test to check if the Correlation Matrix is an Identity matrix.
#If the p-value is low, then we can reject the null hypothesis that the Correlation Matrix is an Identity matrix.
cortest.bartlett(uscrimepc)
```

Principal Component Analysis without rotation
-----------------
A note on Rotation: VARIMAX rotation is used if you expected PCs are highly uncorrelated. Oblimin rotation is used if the expected PCs are correlated.

```{r}
#Note that with the nfactor, we use all variables first and slowly cut down the variables for use.
p1 <- principal(uscrimepc, nfactor=7, rotate="NULL")
#Check the loadings
p1$loadings
scree(uscrimepc, factors=F)
```

Factoring with 2 and 5 factors with No rotation
--------------
```{r}
p2 <- principal(uscrimepc, nfactor = 2, rotate="NULL")
p2$loadings

p5r <- principal(uscrimepc, nfactor=5, rotate="NULL")
p5r$loadings
```

Factoring with 2 and 5 factors with VARIMAX rotation
-----------------
```{r}
#Let's try rotation. default is VARIMAX rotation
p2r <- principal(uscrimepc, nfactor=2)
#Check the loadings
print(p2r$loadings, digits=3, cutoff=0.4, sort=T)

#Rotation with 5 factors
p5r <- principal(uscrimepc, nfactor=5)
print(p5r$loadings, digits=3, cutoff=0.4, sort=T)
```

Factoring with 2 and 5 factors with Oblimin rotation
```{r}
#Try another rotation - Oblimin
p2ro <- principal(uscrimepc, nfactor=2, rotate="oblimin")
print(p2ro$loadings, digits=3, cutoff=0.4, sort=T)

#With 5 factors
p5ro <- principal(uscrimepc, nfactor=5, rotate="oblimin")
p5ro$loadings
```

View the Scores on the principal components
----------
```{r}
head(p2ro$scores)

#Align component scores to the original data and create a new dataframe
uscrime2f <- cbind(uscrime, p2ro$scores)

#Plot the results
plot(uscrime2f$TC1, uscrime2f$TC2, xlab="Component 1", ylab="Component 2", pch=18, col=c("blue", "red", "green", "yellow")[uscrime2f$reg])
text(uscrime2f$TC1, uscrime2f$TC2, uscrime2f$state, cex=0.6, pos=4, col="black")
biplot(p2ro)
```